security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    rest_user: { password: password123 }


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        our_get_artists_firewall:
            pattern: ^/
            anonymous: true
            methods: [GET]

        our_everything_else_artists_firewall:
            pattern: ^/
            anonymous: false
            http_basic:
                provider: in_memory